//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GUI.rc
//
#define IDD_ENCRYPT_FILE                101
#define IDD_MAIN                        101
#define IDD_SETTINGS                    102
#define IDI_LOCK_XP                     104
#define IDI_EXPLORER_XP                 105
#define IDM_ENCRYPT_FILE                106
#define IDD_ABOUT                       107
#define IDD_PROGRESS                    108
#define IDC_MAIN_FILE_TO_ENCRYPT_PATH_EDIT 1001
#define IDC_MAIN_BROWSE_FILE_TO_ENCRYPT_BUTTON 1002
#define IDC_MAIN_ENCRYPT_SPECIFIED_FILE_BUTTON 1003
#define IDC_MAIN_DECRYPT_SPECIFIED_FILE_BUTTON 1004
#define IDC_SETTINGS_ABSOLUTE_STRONG_SECURITY_CHECK 1005
#define IDC_SETTINGS_WIPE_METHOD_COMBO  1006
#define IDC_SETTINGS_BROWSE_KEY_STORAGE_PATH_BUTTON 1007
#define IDC_SETTINGS_KEY_STORAGE_PATH_EDIT 1008
#define IDC_SETTINGS_OK_BUTTON          1009
#define IDC_ABOUT_OK                    1010
#define IDC_PROGRESS_CURRENT_OPERATION_STATIC 1011
#define IDC_PROGRESS_TOTAL_PROGRESS     1012
#define IDC_PROGRESS_STOP_BUTTON        1013
#define IDS_FILE_SECURITY               20000
#define IDS_BROWSE_FOR_KEY_STORAGE_PATH_DIALOG_TITLE 20001
#define IDS_KEY_STORAGE                 20002
#define IDS_EMPTY_KEY_STORAGE_PATH_PROMPT 20003
#define IDS_UNABLE_TO_COMPLETE_ENCRYPT_FILE_OPERATION 20004
#define IDS_UNABLE_TO_COMPLETE_DECRYPT_FILE_OPERATION 20005
#define IDS_UNABLE_TO_RETRIEVE_KEY_STORAGE_PATH 20006
#define IDS_UNABLE_TO_CREATE_KEY_STORAGE_AT_FORMAT 20007
#define IDS_UNABLE_TO_CREATE_COMMUNICATOR 20008
#define IDS_GET_OPEN_FILE_NAME_DIALOG_FAILED_FORMAT 20009
#define IDS_GET_OPEN_FILE_NAME_DIALOG_FAILED_TITLE 20010
#define IDS_FILE_ENCRYPTING             20011
#define IDS_FILE_DECRYPTING             20012
#define IDS_UNABLE_TO_ACCESS_SYSTEM_REGISTRY 20013
#define IDS_SETTINGS                    20014
#define IDS_WIPE_METHODS_COMBO_BOX_INITIALIZING 20015
#define IDS_KEY_STORAGE_PATH_EDIT_INITIALIZING 20016
#define IDS_UNHANDLED_EXCEPTION_REPORT_REQUEST_FORMAT 20017
#define IDS_UNHANDLED_CPP_EXCEPTION_REPORT_REQUEST_FORMAT 20017
#define IDS_FILE_STATE_REQUEST          20018
#define IDS_UNABLE_TO_DETERMINE_FILE_STATE 20019
#define IDS_FILE_ENCRYPTED_SUCCESSFULLY 20020
#define IDS_FILE_DECRYPTED_SUCCESSFULLY 20021
#define IDS_FINISH_BUTTON_TITLE         20022
#define IDS_CLOSE_BUTTON_TITLE          20023
#define IDS_UNABLE_TO_SETUP_PROGRESS_HANDLER 20024
#define IDS_STRING20025                 20025
#define IDS_UNHANDLED_KAA_EXCEPTION_REPORT_REQUEST_FORMAT 20025
#define IDC_ENCRYPT_FILE_EXIT_MENU      40001
#define IDC_ENCRYPT_FILE_SETTINGS_MENU  40002
#define IDC_ENCRYPT_FILE_ABOUT_MENU     40003

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        109
#define _APS_NEXT_COMMAND_VALUE         40004
#define _APS_NEXT_CONTROL_VALUE         1014
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
